run-dist:
	./build/install/app/bin/app

run-dist-help:
	./build/install/app/bin/app -h

run-dist-version:
	./build/install/app/bin/app -V

run-dist-test:
	./build/install/app/bin/app ~/test1.json ~/test2.json